/**:
  ros__parameters:
    debug: true
    auto_type_determined: true 
    predict_time: 0.0
    compensator_type: resistance
    gravity: 9.8
    bullet_speet: 28.0
    lost_time_thres: 0.5
    ekf:
      q: [4e-4, 1e-4, 1e-4, 1e-4]
      r: [4e-2, 1e-2, 1e-2, 1e-2]