/**:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    path: "/home/zcf/csurm/csurm-RMUC2022/red.avi"
    frame_rate: 10
    start_frame: 0
    frame_id: "camera_optical_frame"
    keep_looping: true              #是否循环播放
