image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [3907.89512,    0.     ,  526.92215,
            0.     , 3898.46168,  537.50733,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.013489, 0.755199, -0.005524, -0.025513, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [3888.65601,    0.     ,  516.19743,    0.     ,
            0.     , 3923.14429,  535.42163,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]